#APPEND - APENAS COLOCA SEU VALOR EM ULTIMO NA LISTA.#
#INSERT - PODE DETERMINAR ONDE IRA SER ADICIONADO TAL COISA ADICIONADO O INDEX CORRRETO#
#POP - SERVE PARA APAGAR O NOME DE UMA PESSOA COLOCANDO APENAS O VALOR DE INDEX#
#REMOVE - FAZ A MESMA COISA, SO QUE AO INVES DE INDEX COLOCAMOS APENAS O VALOR#
#SORTED - CRIA UMA LSTA DIFERENTE E ALTERA ELA, PERMANECENDO INTACTA A ORIGINAL#

nomes = [1,2,3,4,4,5324,32,423,423,4,324,2,5,45,32,5]

nome_reserva = sorted(nomes)

print (nome_reserva)